function sessions = read_sessions_csv(filename, startRow, endRow)
    %IMPORTFILE Import numeric data from a text file as a matrix.
    %   SESSIONS = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
    %   default selection.
    %
    %   SESSIONS = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
    %   STARTROW through ENDROW of text file FILENAME.
    %
    % Example:
    %   sessions = importfile('sessions.csv', 1, 168);
    %
    %    See also TEXTSCAN.
    
    % Auto-generated by MATLAB on 2018/11/14 17:13:01
    
    %% Initialize variables.
    delimiter = ',';
    if nargin < 1
        filename = 'sessions.csv';
    end
    if nargin < 2
        startRow = 1;
        endRow = inf;
    end
    
    %% Format string for each line of text:
    %   column1: double (%f)
    %	column2: double (%f)
    %   column3: text (%s)
    %	column4: double (%f)
    %   column5: double (%f)
    %	column6: double (%f)
    %   column7: double (%f)
    %	column8: double (%f)
    %   column9: text (%s)
    %	column10: double (%f)
    %   column11: double (%f)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%f%f%s%f%f%f%f%f%s%f%f%[^\n\r]';
    
    %% Open the text file.
    fileID = fopen(filename,'r');
    
    %% Read columns of data according to format string.
    % This call is based on the structure of the file used to generate this code. If
    % an error occurs for a different file, try regenerating the code from the
    % Import Tool.
    dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
    for block=2:length(startRow)
        frewind(fileID);
        dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
        for col=1:length(dataArray)
            dataArray{col} = [dataArray{col};dataArrayBlock{col}];
        end
    end
    
    %% Close the text file.
    fclose(fileID);
    
    %% Post processing for unimportable data.
    % No unimportable data rules were applied during the import, so no post
    % processing code is included. To generate code which works for unimportable
    % data, select unimportable cells in a file and regenerate the script.
    
    %% Create output variable
    sessions = table(dataArray{1:end-1}, 'VariableNames', {'device_id','session_id','session_type','start_utc_timestamp','start_local_timestamp','stop_utc_timestamp','stop_local_timestamp','duration_sec','stop_cause','noof_subsessions','noof_datafiles'});
    
    %% LeBill
    s1 = 'InputVariables';
    s2 = 'OutputVariableNames';

    % Fix for stop timestamps equal to 0
    idx = sessions.stop_utc_timestamp == 0;
    sessions.stop_utc_timestamp(idx) = sessions.start_utc_timestamp(idx);
    idx = sessions.stop_local_timestamp == 0;
    sessions.stop_local_timestamp(idx) = sessions.start_local_timestamp(idx);
    
    ec1 = rowfun(@unixt2matlab, sessions, s1, 'start_utc_timestamp', s2, 'x');
    ec2 = rowfun(@unixt2matlab, sessions, s1, 'start_local_timestamp', s2, 'x');
    ec3 = rowfun(@unixt2matlab, sessions, s1, 'stop_utc_timestamp', s2, 'x');
    ec4 = rowfun(@unixt2matlab, sessions, s1, 'stop_local_timestamp', s2, 'x');
    
    sessions.start_utc_timestamp = ec1.x;
    sessions.start_local_timestamp = ec2.x;
    sessions.stop_utc_timestamp = ec3.x;
    sessions.stop_local_timestamp = ec4.x;

    ec1 = rowfun(@ (x) cellstr(datestr(x)), sessions, s1, 'start_utc_timestamp', s2, 'x');
    ec2 = rowfun(@ (x) cellstr(datestr(x)), sessions, s1, 'start_local_timestamp', s2, 'x');
    ec3 = rowfun(@ (x) cellstr(datestr(x)), sessions, s1, 'stop_utc_timestamp', s2, 'x');
    ec4 = rowfun(@ (x) cellstr(datestr(x)), sessions, s1, 'stop_local_timestamp', s2, 'x');
    
    sessions.start_utc = ec1.x;
    sessions.start_local= ec2.x;
    sessions.stop_utc = ec3.x;
    sessions.stop_local = ec4.x;
    
    sessions = sessions(:, [1 2 12 13 14 15 3 9 10 11 4 5 6 7 8]);
end
