function devices = read_devices_csv(filename, startRow, endRow)
    %READ_DEVICES_CSV Read a 'devices.csv' file into a table
    %
    %   DEVICES = READ_DEVICES_CSV(FILENAME) Reads data from text file FILENAME
    %   for the default selection.
    %
    %   DEVICES = READ_DEVICES_CSV(FILENAME, STARTROW, ENDROW) Reads data from
    %   rows STARTROW through ENDROW of text file FILENAME.
    %
    % Example:
    %   devices = importfile('devices.csv', 1, 5);
    %
    % Auto-generated by MATLAB on 2018/11/16 13:14:27
    
    %% Initialize variables.
    delimiter = ',';
    if nargin < 1
        filename = 'devices.csv';
    end
    if nargin < 2
        startRow = 1;
        endRow = inf;
    end
    
    %% Format string for each line of text:
    %   column1: double (%f)
    %	column2: text (%s)
    %   column3: text (%s)
    %	column4: text (%s)
    %   column5: double (%f)
    %	column6: double (%f)
    %   column7: double (%f)
    %	column8: double (%f)
    % For more information, see the TEXTSCAN documentation.
    formatSpec = '%f%s%s%s%f%f%f%f%[^\n\r]';
    
    %% Open the text file.
    fileID = fopen(filename,'r');
    
    %% Read columns of data according to format string.
    % This call is based on the structure of the file used to generate this code. If
    % an error occurs for a different file, try regenerating the code from the
    % Import Tool.
    dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
    for block=2:length(startRow)
        frewind(fileID);
        dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
        for col=1:length(dataArray)
            dataArray{col} = [dataArray{col};dataArrayBlock{col}];
        end
    end
    
    %% Close the text file.
    fclose(fileID);
    
    %% Post processing for unimportable data.
    % No unimportable data rules were applied during the import, so no post
    % processing code is included. To generate code which works for unimportable
    % data, select unimportable cells in a file and regenerate the script.
    
    %% Create output variable
    devices = table(dataArray{1:end-1}, 'VariableNames', {'device_id','uuid','model','access_mode','added_on_utc_timestamp','added_on_local_timestamp','last_contact_utc_timestamp','last_contact_local_timestamp'});
    
    %% LeBill
    s1 = 'InputVariables';
    s2 = 'OutputVariableNames';

    ec1 = rowfun(@unixt2matlab, devices, s1, 'added_on_utc_timestamp', s2, 'x');
    ec2 = rowfun(@unixt2matlab, devices, s1, 'added_on_local_timestamp', s2, 'x');
    ec3 = rowfun(@unixt2matlab, devices, s1, 'last_contact_utc_timestamp', s2, 'x');
    ec4 = rowfun(@unixt2matlab, devices, s1, 'last_contact_local_timestamp', s2, 'x');
    
    devices.added_on_utc_timestamp = ec1.x;
    devices.added_on_local_timestamp = ec2.x;
    devices.last_contact_utc_timestamp = ec3.x;
    devices.last_contact_local_timestamp = ec4.x;

    ec1 = rowfun(@ (x) cellstr(datestr(x)), devices, s1, 'added_on_utc_timestamp', s2, 'x');
    ec2 = rowfun(@ (x) cellstr(datestr(x)), devices, s1, 'added_on_local_timestamp', s2, 'x');
    ec3 = rowfun(@ (x) cellstr(datestr(x)), devices, s1, 'last_contact_utc_timestamp', s2, 'x');
    ec4 = rowfun(@ (x) cellstr(datestr(x)), devices, s1, 'last_contact_local_timestamp', s2, 'x');
    
    devices.added_on_utc = ec1.x;
    devices.added_on_local= ec2.x;
    devices.last_contact_utc = ec3.x;
    devices.last_contact_local = ec4.x;
    
    devices = devices(:, [1 4 3 9 10 11 12 5 6 7 8 2]);
end
